'use strict';
const DATA = __DATA__;
const DAY=DATA.days.at(-1), BLOCKS=DATA.blocks, DAYS=DATA.days;
const total=Object.values(DAY.counts).reduce((a,b)=>a+b,0);
const weekly=id=>DAYS.slice(-7).reduce((a,d)=>a+d.counts[id],0);
const allweek=BLOCKS.reduce((a,b)=>a+weekly(b.id),0);
const prevweek=BLOCKS.reduce((a,b)=>a+DAYS.slice(-14,-7).reduce((s,d)=>s+d.counts[b.id],0),0);
const delta=((allweek/prevweek-1)*100).toFixed(1);
const tone = (bg,surface,surface2,ink,muted,line,primary,soft,warn,on='#062126')=>({bg,surface,surface2,ink,muted,line,primary,onPrimary:on,primarySoft:soft,onPrimarySoft:ink,inverse:ink,onInverse:bg,inversePrimary:primary,warn});
const PROJECT={slug:'fieldops-future',title:'FieldOps, reimagined.',intro:'A cinematic analytics workspace for the final film. Start with the atmosphere, then choose how each tab tells the orchard’s story. Every number comes from the committed demo season, shown on June 4.',steps:['Choose a look, typeface and navigation. Those choices carry through every screen.','Click a screen to inspect it at full size. Mix options across rows.','Save your picks, then tell me in chat.'],findingsTitle:'What changes',findings:[{lead:'Give analytics a home.',text:'The current dashboard places species, trap and weather analytics below the replay. Dedicated tabs bring each into focus.'},{lead:'Design for the camera.',text:'The June 4 snapshot contains 132 codling moths, 18 traps and one open spray window. Those facts become the visual hierarchy.'},{lead:'Borrow the visual language.',text:'Read-only review of your MJH Skills styles informed the cinematic color layers; SIFT informed the structured navigation and evidence panels.'}],frame:{kind:'browser',w:1440,h:900,tile:360,nowTile:240},toggles:{mode:true,textSize:true,defaultMode:'dark',defaultTs:1},swatch:['bg','primary','warn'],looks:{
ion:{name:'Ion atlas',radius:{rl:12,rm:8,rbtn:7,rchip:5},dark:tone('#080f1b','#101b2b','#1a293c','#edf6ff','#9daec3','#263649','#70d8ed','#153645','#ffce86'),light:tone('#edf3f9','#ffffff','#e2eaf3','#10243b','#526780','#cbd8e6','#08657b','#d9eff4','#885000','#ffffff')},
vice:{name:'Dusk observatory',radius:{rl:14,rm:9,rbtn:8,rchip:5},dark:tone('#100e1d','#1c182e','#29233e','#faf4ff','#b9aecb','#39304c','#c5abff','#362955','#ffd398','#251744'),light:tone('#f4eff9','#fffaff','#eae1f3','#2d1b42','#6f5b83','#dacfe6','#6c42a6','#ebe0fa','#855200','#ffffff')},
current:{name:'Current orchard',radius:{rl:16,rm:12,rbtn:999,rchip:999},dark:tone('#12251e','#1b3027','#263d31','#eaf3ed','#a5b9ab','#3a5144','#9ed3b8','#254b3a','#ffd398'),light:tone('#f4f6f1','#ffffff','#e8ece3','#1f3229','#5a6b61','#d9dfd5','#126d58','#d8ede5','#885000','#ffffff')}
},types:{space:{name:'Space + Manrope',fd:'Space',fb:'Manrope',dw:650,dls:'-1px'},plex:{name:'Plex precision',fd:'Plex',fb:'Plex',dw:600,dls:'-.8px'}},decisions:[]};
const names=['Overview','Pest analytics','Orchard blocks','Trap lab','Weather & timing','FieldOps intelligence'];
const icons=['grid','bars','home','search','clock','note'];
function shell(ctx,active,body,{title=names[active],subtitle='Nashoba Ridge Orchard / Bolton, Massachusetts',action='Export view'}={}){return K.web(`<div class="fx-app ${ctx.nav==='top'?'fx-horizontal':''}"><aside class="fx-nav"><div class="fx-brand"><i class="fx-logo"></i>FieldOps</div><div class="fx-navlinks">${names.map((n,i)=>`<div class="fx-link ${i===active?'fx-active':''}">${ic(icons[i],18)}<span>${n}</span></div>`).join('')}</div><div class="fx-navfoot"><span class="fx-dot"></span>Local intelligence<br><br>Nashoba Ridge<br>2026 season<br><br>Demo dataset</div></aside><div class="fx-work"><div class="fx-top"><b>Orchard workspace</b><span class="fx-muted">/ 2026 season</span><span class="fx-spacer"></span><span class="fx-pill">${ic('cal',13)} Jun 4, 2026</span><span class="fx-pill">18 traps</span><span class="fx-letter">HN</span></div><div class="fx-content"><div class="fx-title"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="fx-button fx-quiet">${ic('download',15)}${action}</div></div>${body}<div class="fx-footer"><span>FieldOps / Orchard intelligence</span><span>Demo season • Snapshot June 4, 2026</span></div></div></div></div>`)}
function kpis(){return `<div class="fx-kpis">${[['Codling moths today',total,'Across all 18 traps'],['7-day catch',allweek,`${+delta>=0?'+':''}${delta}% vs previous 7 days`],['Open spray windows','01','Block C / Gala'],['Thermal accumulation','17.0','Degree-days today']].map(([t,n,f])=>`<div class="fx-kpi"><div class="fx-label">${t}</div><div class="fx-number">${n}</div><div class="fx-small">${f}</div></div>`).join('')}</div>`}
function map(iso=false){let contours=Array.from({length:13},(_,i)=>`<ellipse class="fx-contour" cx="390" cy="220" rx="${240+i*24}" ry="${95+i*16}" transform="rotate(-16 390 220)"/>`).join('');let polys=BLOCKS.map((b,i)=>{let x=70+(i%3)*214,y=76+Math.floor(i/3)*143,open=i===2;let c=open?'var(--warn)':'var(--primary)';let rows=Array.from({length:8},(_,j)=>`<path d="M${x+20+j*20} ${y+15}l-9 105" stroke="${c}" opacity=".18" stroke-width="3" stroke-dasharray="2 6"/>`).join('');return `<g><path d="M${x+8} ${y}L${x+197} ${y-7}L${x+187} ${y+125}L${x} ${y+117}Z" fill="${c}" fill-opacity="${open?'.14':'.055'}" stroke="${c}" stroke-opacity="${open?'1':'.4'}" stroke-width="${open?2:1}"/>${rows}<rect x="${x+16}" y="${y+16}" width="168" height="49" rx="5" fill="var(--surface)" fill-opacity=".94"/><text class="fx-mapletter" x="${x+27}" y="${y+49}" fill="${c}">${b.name.slice(-1)}</text><text x="${x+62}" y="${y+36}" fill="var(--ink)">${b.variety}</text><text x="${x+62}" y="${y+55}" fill="${c}">${open?'Window open':'Accumulating'}</text>${[0,1,2].map((n)=>`<circle cx="${x+37+n*60}" cy="${y+91}" r="4" fill="${c}"/><circle cx="${x+37+n*60}" cy="${y+91}" r="9" fill="none" stroke="${c}" stroke-opacity=".22"/>`).join('')}</g>`}).join('');return `<div class="fx-map"><svg viewBox="0 0 780 390" role="img" aria-label="Schematic orchard, six blocks, Block C spray window open">${contours}<path d="M30 52L729 42 731 358 29 357Z" fill="none" stroke="var(--line)" stroke-dasharray="4 5"/><g ${iso?'transform="translate(115 -5) rotate(8 350 195) skewX(-14) scale(.85 1)"':''}>${polys}</g><text x="728" y="28" fill="var(--muted)">N ↑</text></svg><div class="fx-maplabel"><span>Schematic orchard • ${BLOCKS.reduce((s,b)=>s+b.acres,0).toFixed(1)} acres</span><span>◎ 18 trap locations</span></div></div>`}
function plot(kind='catch',small=false){const W=740,H=220,L=38,R=715,T=15,B=187;let vals=DAYS.map(d=>kind==='weather'?(d.tmin_f+d.tmax_f)/2:kind==='dd'?d.blocks['block-c'].dd_since_biofix:d.counts['block-c']);let other=DAYS.map(d=>kind==='weather'?d.tmax_f:kind==='dd'?d.blocks['block-a'].dd_since_biofix:Object.values(d.counts).reduce((a,b)=>a+b,0)/6);let max=kind==='dd'?350:kind==='weather'?90:50;let pt=(a)=>a.map((v,i)=>`${L+(R-L)*i/(a.length-1)},${B-(B-T)*v/max}`).join(' ');let line=(a)=>'M'+pt(a).replaceAll(' ',' L');return `<svg class="fx-plot" viewBox="0 0 ${W} ${H}" aria-label="${kind} chart from April 15 to June 4">${[0,.5,1].map(f=>`<line x1="${L}" x2="${R}" y1="${B-(B-T)*f}" y2="${B-(B-T)*f}" stroke="var(--line)"/><text x="${L-9}" y="${B-(B-T)*f+4}" text-anchor="end">${Math.round(max*f)}</text>`).join('')}${kind==='dd'?`<rect x="${L}" y="${T}" width="${R-L}" height="${(B-T)*100/350}" fill="var(--warn)" opacity=".07"/><text x="${L+10}" y="${T+20}" style="fill:var(--warn)">Spray window 250–350 DD</text>`:''}<path d="${line(vals)} L${R},${B} L${L},${B} Z" fill="var(--primary)" opacity=".07"/><polyline points="${pt(other)}" fill="none" stroke="var(--warn)" stroke-width="2" stroke-dasharray="5 5"/><polyline points="${pt(vals)}" fill="none" stroke="var(--primary)" stroke-width="3" stroke-linejoin="round"/><circle cx="${R}" cy="${B-(B-T)*vals.at(-1)/max}" r="4" fill="var(--primary)"/>${[['Apr 15','2026-04-15'],['May 1','2026-05-01'],['May 15','2026-05-15'],['Jun 4','2026-06-04']].map(([t,date],i)=>`<text x="${L+DAYS.findIndex(d=>d.date===date)*(R-L)/(DAYS.length-1)}" y="215" text-anchor="${i===3?'end':'start'}">${t}</text>`).join('')}</svg>`}
function chartCard(kind='catch'){return `<div class="fx-card"><div class="fx-cardhead"><h2>${kind==='dd'?'The biological clock':kind==='weather'?'Temperature profile':'Flight activity'}</h2><span class="fx-small">Apr 15 – Jun 4</span></div><div class="fx-chartkey"><span><i class="fx-linekey"></i>${kind==='weather'?'Daily mean':'Block C'}</span><span><i class="fx-linekey fx-dashed"></i>${kind==='weather'?'Daily high':kind==='dd'?'Block A':'Farm mean / block'}</span></div><div class="fx-pad">${plot(kind)}</div></div>`}
function alertCard(){return `<div class="fx-card fx-alert fx-pad"><div class="fx-between"><span class="fx-tag">Spray window open</span>${ic('bell',18)}</div><h2>Block C is ready<br>for intervention.</h2><p>Gala / 3.4 acres</p><div class="fx-number fx-warn">261<small> DD</small></div><div class="fx-progress fx-amber"><i style="width:74.6%"></i></div><div class="fx-between fx-small"><span>Biofix May 8</span><span>350 DD closes</span></div><div class="fx-rule"></div><div class="fx-between"><span class="fx-small">Threshold crossed today</span>${ic('chev',20)}</div></div>`}
function ranks(){return `<div class="fx-card"><div class="fx-cardhead"><h2>Next in focus</h2><span class="fx-small">Degree-days</span></div><div class="fx-rows">${[0,1,4].map(i=>{let b=BLOCKS[i];return `<div class="fx-row"><span class="fx-letter">${b.name.slice(-1)}</span><div><b>${b.name}</b><div class="fx-small">${b.variety}</div></div><span class="fx-spacer"></span><b>${DAY.blocks[b.id].dd_since_biofix}</b></div>`}).join('')}</div></div>`}
function overview(ctx,alt=false){let upper=alt?`<div class="fx-grid">${chartCard()}${alertCard()}</div><div class="fx-grid fx-bottom"><div class="fx-card"><div class="fx-cardhead"><h2>Orchard atlas</h2><span class="fx-small">Block C selected</span></div>${map(true)}</div>${ranks()}</div>`:`<div class="fx-grid"><div class="fx-card"><div class="fx-cardhead"><h2>Orchard atlas</h2><span class="fx-tag">1 window open</span></div>${map()}</div>${alertCard()}</div><div class="fx-grid fx-bottom">${chartCard()}${ranks()}</div>`;return shell(ctx,0,kpis()+upper,{title:alt?'The season, in focus.':'Your orchard. In perspective.',subtitle:'Thursday, June 4 / One block has entered its spray window.'})}
function heatmap(){return `<div class="fx-card"><div class="fx-cardhead"><h2>Catch intensity by week</h2><span class="fx-small">Codling moth</span></div><div class="fx-matrix"><span></span>${Array.from({length:8},(_,i)=>`<span class="fx-small">${i+1}</span>`).join('')}${BLOCKS.map(b=>`<b>${b.name.slice(-1)}</b>${Array.from({length:8},(_,i)=>{let v=DAYS.slice(i*7,i*7+7).reduce((s,d)=>s+d.counts[b.id],0);return `<span class="fx-cell" style="--heat:${Math.max(4,v/230*90)}" title="${v} moths"></span>`}).join('')}`).join('')}</div><div class="fx-caption">Week 1 begins Apr 15. Week 8 includes data through Jun 4.</div></div>`}
function speciesRows(){return `<div class="fx-card"><div class="fx-cardhead"><h2>Species by block</h2><span class="fx-small">Last 7 days</span></div><div class="fx-rows">${BLOCKS.map(b=>{let c=weekly(b.id),o=DATA.species[b.id].oriental_fruit_moth.slice(-7).reduce((a,b)=>a+b,0);return `<div class="fx-row"><b style="width:66px">${b.name}</b><div style="flex:1"><div class="fx-progress" style="margin:5px 0"><i style="width:${c/220*100}%"></i></div><div class="fx-progress fx-amber" style="margin:5px 0"><i style="width:${o/220*100}%"></i></div></div><span class="fx-small" style="width:76px;text-align:right">${c} / ${o}</span></div>`}).join('')}</div><div class="fx-caption">Upper bar: codling moth / lower bar: oriental fruit moth<br>Spotted lanternfly: none in this demo season.</div></div>`}
function pests(ctx,alt){return shell(ctx,1,`<div class="fx-strip"><span class="fx-picked">Codling moth</span><span>Oriental fruit moth</span><span>Spotted lanternfly</span><span>All blocks</span></div>${kpis()}${alt?`<div class="fx-grid fx-equal">${heatmap()}${speciesRows()}</div><div class="fx-bottom">${chartCard()}</div>`:`${chartCard()}<div class="fx-grid fx-bottom">${heatmap()}${speciesRows()}</div>`}`,{title:alt?'Where pressure is building.':'Read the flight.'})}
function blocks(ctx,alt){let grid=`<div class="fx-tilegrid">${BLOCKS.map(b=>`<div class="fx-card fx-pad ${b.id==='block-c'?'fx-alert':''}"><div class="fx-between"><span class="fx-letter">${b.name.slice(-1)}</span><span class="fx-small">${b.acres} acres</span></div><h2 style="margin-top:18px">${b.variety}</h2><div class="fx-number">${DAY.blocks[b.id].dd_since_biofix}<small> DD</small></div><span class="fx-tag">${b.id==='block-c'?'Window open':'Accumulating'}</span><div class="fx-progress"><i style="width:${DAY.blocks[b.id].dd_since_biofix/350*100}%"></i></div><div class="fx-small">${DAY.counts[b.id]} moths today / ${weekly(b.id)} this week</div></div>`).join('')}</div>`;return shell(ctx,2,alt?grid:`<div class="fx-grid"><div class="fx-card"><div class="fx-cardhead"><h2>Farm boundary & blocks</h2><span class="fx-small">Selected: C</span></div>${map(true)}<div class="fx-caption">Schematic map. Select a block for its pest history and timing.</div></div>${alertCard()}</div><div class="fx-bottom">${grid}</div>`,{title:alt?'Six blocks. One clear picture.':'Every block has a story.'})}
function trapTable(){return `<div class="fx-card"><table class="fx-table"><thead><tr><th>Trap</th><th>Block</th><th>Today</th><th>7-day catch</th><th>Season context</th></tr></thead><tbody>${Object.entries(DAY.traps).sort((a,b)=>b[1]-a[1]).map(([id,v])=>{let n=DAYS.slice(-7).reduce((s,d)=>s+d.traps[id],0);return `<tr class="${id.includes('block-c')?'fx-selected':''}"><td>${id}</td><td>${id.slice(6,7).toUpperCase()}</td><td><b>${v}</b></td><td>${n}</td><td><div class="fx-progress" style="width:100px;margin:0"><i style="width:${n/90*100}%"></i></div></td></tr>`}).join('')}</tbody></table></div>`}
function traps(ctx,alt){return shell(ctx,3,`<div class="fx-strip"><span class="fx-picked">All 18 traps</span><span>Block C</span><span>Codling moth</span><span>Highest catch first</span></div>${alt?trapTable():`<div class="fx-grid"><div class="fx-card"><img class="fx-image fx-imagewide" src="${IMG.trap}" alt="Synthetic sticky trap sample containing 12 codling moths"><div class="fx-caption">Synthetic reference image / trap_03_codling012.jpg<br>Sample image is separate from the June 4 daily counts.</div></div><div class="fx-card fx-pad"><span class="fx-tag">Reference capture</span><h2 style="margin-top:18px">Inspect the evidence.</h2><div class="fx-number">12<small> codling moths</small></div><p>Manifest ground truth for this synthetic trap card. It is a visual reference, not a fresh model result.</p><div class="fx-rule"></div><div class="fx-small">June 4 • Orchard snapshot</div><div class="fx-row"><span>Traps reporting</span><span class="fx-spacer"></span><b>18 / 18</b></div><div class="fx-row"><span>Codling catch</span><span class="fx-spacer"></span><b>132</b></div><div class="fx-row"><span>Block C catch</span><span class="fx-spacer"></span><b>26</b></div></div></div><div class="fx-bottom">${trapTable()}</div>`}`,{title:alt?'Every reading, accounted for.':'From image to intelligence.'})}
function ddRanks(){return `<div class="fx-card"><div class="fx-cardhead"><h2>Progress toward the spray window</h2><span class="fx-small">Opens at 250 DD</span></div><div class="fx-ddlist">${BLOCKS.slice().sort((a,b)=>DAY.blocks[b.id].dd_since_biofix-DAY.blocks[a.id].dd_since_biofix).map(b=>`<div class="fx-ddrow"><b>${b.name}</b><div class="fx-progress ${b.id==='block-c'?'fx-amber':''}"><i style="width:${DAY.blocks[b.id].dd_since_biofix/350*100}%"></i></div><b>${DAY.blocks[b.id].dd_since_biofix}</b></div>`).join('')}</div><div class="fx-caption">Degree-days since each block’s biofix. Base 50°F, upper threshold 88°F.</div></div>`}
function weather(ctx,alt){return shell(ctx,4,`${kpis()}${alt?`<div class="fx-grid">${ddRanks()}${alertCard()}</div><div class="fx-bottom">${chartCard('weather')}</div>`:`${chartCard('weather')}<div class="fx-grid fx-equal fx-bottom">${chartCard('dd')}${ddRanks()}</div>`}`,{title:alt?'The right moment to act.':'Weather becomes a decision.',subtitle:'Observed demo weather / 55°F low, 79°F high / June 4'})}
function evidence(){return `<div class="fx-card fx-pad"><h2>The evidence chain</h2>${[['01','Sustained catch','Block C biofix was set on May 8.'],['02','Heat accumulation','261 degree-days have accumulated since biofix.'],['03','Window opens','The configured spray range is 250–350 DD.'],['04','Grower decision','Review the spray window and local treatment plan.']].map(([n,t,p])=>`<div class="fx-step"><b>${n}</b><div><strong>${t}</strong><p>${p}</p></div></div>`).join('')}<div class="fx-small">Deterministic season facts / snapshot June 4</div></div>`}
function agent(ctx,alt){return shell(ctx,5,alt?`<div class="fx-grid"><div class="fx-card fx-pad"><div class="fx-orb"></div><div class="fx-brief">Good timing changes<br>everything.</div><p style="font-size:calc(17px * var(--ts));margin-top:20px">Block C has entered its spray window at 261 DD. Block A is next in line at 246.5 DD, only 3.5 DD below the opening threshold.</p><div class="fx-rule"></div><div class="fx-between"><span class="fx-small">Season briefing / June 4</span><span class="fx-button">Read supporting facts</span></div><div class="fx-question">Ask a follow-up ${ic('note',18)}</div></div>${evidence()}</div>`:`<div class="fx-grid"><div class="fx-card fx-pad"><span class="fx-tag">FieldOps intelligence</span><div class="fx-question">Why does Block C need attention? ${ic('user',18)}</div><div class="fx-chat"><div class="fx-brief">Its spray window<br>opened today.</div><p>Block C has reached <b class="fx-accent">261 degree-days</b> since its May 8 biofix. The configured window begins at 250 DD and closes at 350 DD.</p><p>Today’s traps recorded <b>26 codling moths</b>. Block A is closest to following, at 246.5 DD.</p><div class="fx-strip" style="margin-top:20px"><span>Block C</span><span>Degree-day model</span><span>Trap counts</span></div></div><div class="fx-question">Ask about your orchard… ${ic('chev',20)}</div><div class="fx-small" style="margin-top:12px">Preview answer from committed season facts</div></div>${evidence()}</div>`,{title:alt?'Your orchard, explained.':'Ask. Understand. Act.',subtitle:'A clear explanation, with the facts always within reach.'})}
function cinema(ctx,alt){if(alt)return shell(ctx,0,`<div class="fx-grid"><div class="fx-card fx-pad"><span class="fx-small">Chapter 03 / The decision</span><div class="fx-brief" style="margin:20px 0">The window opens.<br>The grower knows.</div><p>June 4. Block C reaches 261 degree-days.</p><div class="fx-rule"></div><div class="fx-chartkey"><span><i class="fx-linekey"></i>Block C</span><span><i class="fx-linekey fx-dashed"></i>Block A</span></div>${plot('dd')}<div class="fx-chapters"><span>01 Detect</span><span>02 Understand</span><b>03 Act</b></div></div>${alertCard()}</div><div class="fx-bottom">${chartCard()}</div>`,{title:'The season story.',subtitle:'Presentation mode / chapter navigation',action:'Exit presentation'});return K.web(`<div class="fx-app"><div class="fx-cinema" style="width:100%"><div class="fx-between"><div class="fx-brand"><i class="fx-logo"></i>FieldOps</div><span class="fx-small">Nashoba Ridge / June 4, 2026</span></div><h1>The orchard speaks.<br><span class="fx-accent">Know when to act.</span></h1><div class="fx-grid"><div class="fx-card">${map(true)}</div>${alertCard()}</div><div class="fx-chapters"><b>03 / The decision</b><span>Block C</span><span>261 degree-days</span><span>Spray window open</span><span class="fx-spacer"></span><span>Next chapter ${ic('chev',16)}</span></div><div class="fx-small" style="margin-top:20px">Demo season / Schematic orchard</div></div></div>`)}
const option=(id,name,desc,r,value)=>({id,name,desc,r,...(value?{value}:{})});
const dec=(id,group,name,ask,why,opts,now='current',rec='A')=>({id,group,name,ask,why:[why],opts,rec,now,nowCap:'Current dashboard / June 4'});
PROJECT.decisions=[
{...dec('look','Foundation','Atmosphere','Which world should FieldOps live in?','The current pale orchard view lacks the cinematic depth requested for the video.',[option('A','Ion atlas','Deep blue instrument panels, crisp cyan data and a warm treatment signal.',c=>overview(c,false),'ion'),option('B','Dusk observatory','Violet layers and luminous lavender, with the flight curve leading the composition.',c=>overview(c,true),'vice')]),drives:'look',nowValue:'current'},
{...dec('type','Foundation','Typography','Expressive or precise?','Numbers and narrative need distinct hierarchy at recording size.',[option('A','Space + Manrope','Geometric display type for headlines and readings; restrained Manrope for detail.',c=>overview(c,false),'space'),option('B','Plex precision','A single technical family makes the workspace feel like a scientific instrument.',c=>overview(c,false),'plex')]),drives:'type',nowValue:'plex'},
{...dec('navigation','Foundation','Navigation','A persistent rail or a wide workspace?','The existing single page has no tabs and leaves detailed analytics below the replay.',[option('A','Workspace rail','Named tabs stay on the left, with the orchard context anchored below.',c=>overview(c,false),'rail'),option('B','Top workspace','A horizontal tab bar opens up the full width for charts and maps.',c=>overview(c,false),'top')]),drives:'nav',nowValue:'rail'},
dec('overview','Analytics tabs','Overview','Lead with the orchard or its signals?','The current view makes the map prominent but compresses the decision and flight curve.',[option('A','Orchard atlas','A large block map sits beside the open spray window; trends continue below.',c=>overview(c,false)),option('B','Signal desk','The flight chart and decision lead; the map becomes supporting context.',c=>overview(c,true))]),
dec('pests','Analytics tabs','Pest activity','A story over time or a comparison across blocks?','Species bars and the weekly heatmap are currently below the main dashboard.',[option('A','Flight observatory','A broad trend chart leads, with the weekly matrix and species comparison below.',c=>pests(c,false)),option('B','Pressure matrix','Catch intensity and species comparisons lead; the flight history supports them.',c=>pests(c,true))],'analytics'),
dec('blocks','Analytics tabs','Orchard blocks','Explore a map or scan the whole farm?','Current block details are spread between the map, degree-day clock and analytics.',[option('A','Spatial inspector','A tilted schematic makes place tangible, with selected block details beside it.',c=>blocks(c,false)),option('B','Block portfolio','Six comparable block cards show thermal progress, variety and daily catch.',c=>blocks(c,true))]),
dec('traps','Analytics tabs','Trap lab','Visual evidence or a precise reading ledger?','The trap table exists, but reviewing capture imagery needs a dedicated surface.',[option('A','Evidence lab','A reference trap capture and its ground truth sit above the daily reading ledger.',c=>traps(c,false)),option('B','Reading ledger','A full-width sortable-table direction puts every trap and weekly total first.',c=>traps(c,true))],'analytics'),
dec('timing','Analytics tabs','Weather & timing','Explain the weather or prioritize the next window?','Weather and degree-day charts are separate panels below the fold today.',[option('A','Climate lens','Temperature history leads into thermal accumulation and block readiness.',c=>weather(c,false)),option('B','Window planner','Ranked degree-day progress and the open window lead; weather is supporting evidence.',c=>weather(c,true))],'analytics','B'),
dec('intelligence','Analytics tabs','Intelligence','A conversation or a prepared briefing?','The current agent is a small transcript in a narrow side panel.',[option('A','Evidence dialogue','A full conversation canvas pairs every explanation with the underlying facts.',c=>agent(c,false)),option('B','Daily briefing','A calm intelligence sphere introduces a concise orchard brief and evidence chain.',c=>agent(c,true))],'current','B'),
dec('film','Presentation','Video mode','An immersive chapter or a guided dashboard?','The final deliverable is a video, so each beat needs a clear visual focus.',[option('A','Cinematic chapters','Hide application chrome and stage the map, timing and decision as a film chapter.',c=>cinema(c,false)),option('B','Guided workspace','Keep the product navigation visible and progress through the season in chapters.',c=>cinema(c,true))])
];
