(function(){
'use strict';
const data=window.FIELDOPS_TIMELINE;
if(!data?.days?.length){document.getElementById('app').innerHTML='<main class="boot-state"><h1>No season data found</h1><p>Keep the dashboard folder together with its local data assets, then reload.</p></main>';return;}
const tabs=[['overview','Overview','grid'],['pests','Pest analytics','bars'],['orchard','Orchard blocks','home'],['traps','Trap lab','search'],['timing','Weather & timing','clock'],['intelligence','Intelligence','spark']];
const speciesNames={codling_moth:'Codling moth',oriental_fruit_moth:'Oriental fruit moth',spotted_lanternfly:'Spotted lanternfly'};
const statusNames={watching:'Monitoring',accumulating:'Accumulating',spray_window:'Window open',window_closed:'Window closed'};
const qs=new URLSearchParams(location.search),dateIndex=date=>data.days.findIndex(d=>d.date===date);
let state={index:Math.max(0,dateIndex(qs.get('date')||'2026-06-04')),block:data.blocks.some(b=>b.id===qs.get('focus'))?qs.get('focus'):'block-c',species:Object.hasOwn(speciesNames,qs.get('species'))?qs.get('species'):'codling_moth',tab:tabs.some(t=>t[0]===qs.get('tab'))?qs.get('tab'):'overview',range:'season',presentation:qs.get('present')==='1',chapter:Math.max(0,Math.min(2,Number(qs.get('chapter')||2))),playing:false,speed:1};
let timer=null,toastTimer=null,rendering=false,mapController=null;
const TRIGGER_URL='http://127.0.0.1:8765/trigger',phoned=new Set(),firstOf={};
data.days.forEach((d,i)=>(d.events||[]).forEach(e=>{if(!firstOf[e.type])firstOf[e.type]={i,block:e.block_id}}));
const $=id=>document.getElementById(id);
let theme;try{theme=localStorage.getItem('fieldops-theme')}catch{}document.documentElement.dataset.theme=theme==='light'?'light':'dark';
const actions={update,navigate:tab=>update({tab}),openAgent:question=>window.FOIntelligence?.open(question)};
const context=()=>window.FOModel.context(state,actions);
window.FieldOps={getState:()=>({...state}),getContext:context,update,stop:()=>setPlaying(false),getMapState:()=>mapController?.getState()||null};
function toast(message){$('app-toast').textContent=message;$('app-toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('app-toast').classList.remove('visible'),4000)}
function url(){const p=new URLSearchParams(location.search);p.set('date',data.days[state.index].date);p.set('focus',state.block);p.set('tab',state.tab);p.set('species',state.species);p.delete('fire');if(state.presentation){p.set('present','1');p.delete('chapter')}else{p.delete('present');p.delete('chapter')}try{history.replaceState(null,'',location.pathname+'?'+p.toString()+location.hash)}catch{}}
function update(patch){const oldTab=state.tab;state={...state,...patch};state.index=Math.max(0,Math.min(data.days.length-1,Number(state.index)||0));if(state.index===0)phoned.clear();if(!data.blocks.some(b=>b.id===state.block))state.block='block-c';if(!tabs.some(t=>t[0]===state.tab))state.tab='overview';if(!Object.hasOwn(speciesNames,state.species))state.species='codling_moth';url();render();if(oldTab!==state.tab)window.scrollTo({top:0,behavior:'instant'})}
// Texts the phone via the local tool server (python -m fieldops.api) when playback moves forward over the
// first biofix or the first spray window of the season. no-cors keeps a page opened from disk free of
// preflights; if the server is down nothing happens and the screen is unaffected. Scrubbing never texts.
function notifyPhone(from,to){for(let i=from+1;i<=to;i++)for(const e of data.days[i].events||[]){const f=firstOf[e.type];if((e.type==='biofix'||e.type==='spray_window_open')&&f&&f.i===i&&f.block===e.block_id&&!phoned.has(e.type)){phoned.add(e.type);try{fetch(TRIGGER_URL,{method:'POST',mode:'no-cors',body:JSON.stringify({date:data.days[i].date,block_id:e.block_id,type:e.type})}).catch(()=>{})}catch{}}}}
function step(to){const from=state.index;update({index:to});notifyPhone(from,state.index)}
function setPlaying(on){clearInterval(timer);state.playing=on;if(on){if(state.index>=data.days.length-1){state.index=0;phoned.clear()}timer=setInterval(()=>{if(state.index>=data.days.length-1)return setPlaying(false);step(state.index+1)},30000/data.days.length/state.speed)}render()}
function title(ctx){const titles={overview:['Your orchard. In perspective.','One connected view of pest pressure, place and timing.'],pests:['Read the flight.','Follow the signals. Understand the season.'],orchard:['Every block has a story.','Explore the orchard, from boundary to individual trap.'],traps:['From image to intelligence.','Inspect the evidence behind each observation.'],timing:['The right moment to act.','A clear view of the biological clock across your orchard.'],intelligence:['Your orchard, explained.','A daily briefing with the supporting facts close at hand.']};return titles[ctx.tab]}
function kpis(ctx){const week=ctx.blocks.reduce((s,b)=>s+ctx.weekly(b.id),0),prior=ctx.blocks.reduce((s,b)=>s+ctx.weekly(b.id,ctx.species,7),0),change=prior?((week/prior-1)*100):null;const open=ctx.blocks.filter(b=>ctx.status(b.id).status==='spray_window');const rows=[[speciesNames[ctx.species]+' today',ctx.num(ctx.total()),'Across 18 orchard traps','bars'],['Seven-day catch',ctx.num(week),change===null?'No prior catches to compare':`${change>=0?'+':''}${ctx.num(change,1)}% vs previous 7 days`,'grid'],['Open spray windows',String(open.length).padStart(2,'0'),open.length?open.map(b=>b.name).join(', ')+' / codling moth':'Codling moth timing model','bell'],['Thermal accumulation',ctx.num(ctx.day.dd_today,1),'Degree-days today / base 50°F','sun']];return `<div class="fx-kpis">${rows.map(([t,n,f,ic])=>`<div class="fx-kpi"><div class="metric-top"><span class="fx-label">${ctx.esc(t)}</span>${ctx.icon(ic,16)}</div><div class="fx-number">${n}</div><div class="fx-small">${ctx.esc(f)}</div></div>`).join('')}</div>`}
function selectedCard(ctx,{compact=false}={}){const b=ctx.blocks.find(b=>b.id===ctx.block),s=ctx.status(),th=ctx.timeline.thresholds;let heading={watching:'Watching for the first sustained flight.',accumulating:'The biological clock is running.',spray_window:'The treatment window is open.',window_closed:'This spray window has closed.'}[s.status];return `<section class="fx-card focus-card ${s.status==='spray_window'?'fx-alert':''}" aria-label="${ctx.esc(b.name)} timing"><div class="fx-pad"><div class="fx-between"><span class="fx-tag status-${s.status}">${statusNames[s.status]}</span><span class="block-badge">${b.name.slice(-1)}</span></div><div class="focus-crop">${ctx.esc(b.name)} / ${ctx.esc(b.variety)}</div><h2>${heading}</h2><div class="focus-dd"><strong>${ctx.num(s.dd_since_biofix,s.dd_since_biofix%1?1:0)}</strong><span>degree-days<br>since biofix</span></div><div class="window-track" aria-label="${ctx.num(s.dd_since_biofix,1)} degree-days; window ${th.spray_open_dd} to ${th.spray_close_dd}"><span style="left:${th.spray_open_dd/th.spray_close_dd*100}%"></span><i style="width:${Math.min(100,s.dd_since_biofix/th.spray_close_dd*100)}%"></i></div><div class="fx-between fx-small"><span>0 DD</span><span>${th.spray_open_dd} opens</span><span>${th.spray_close_dd} closes</span></div><div class="focus-facts"><div><span>Biofix</span><b>${ctx.dateLabel(s.biofix_date)}</b></div><div><span>Codling today</span><b>${ctx.count(b.id,ctx.index,'codling_moth')}</b></div><div><span>${s.status==='accumulating'&&s.projected_open?'Est. window':'Block area'}</span><b title="${s.status==='accumulating'&&s.projected_open?'Climate-normal estimate, not a forecast':''}">${s.status==='accumulating'&&s.projected_open?'Around '+ctx.dateLabel(s.projected_open):b.acres+' acres'}</b></div></div><button class="fx-button focus-ask" data-action="ask" data-question="Why is ${ctx.esc(b.name)} ${statusNames[s.status].toLowerCase()}?">${ctx.icon('spark',16)} Explain this window</button></div></section>`}
function nextBlocks(ctx){const ranked=ctx.blocks.filter(b=>ctx.status(b.id).status==='accumulating').sort((a,b)=>ctx.status(b.id).dd_since_biofix-ctx.status(a.id).dd_since_biofix);return `<section class="fx-card next-card"><div class="fx-cardhead"><h2>Next in focus</h2><span class="fx-small">To ${ctx.timeline.thresholds.spray_open_dd} DD</span></div><div class="fx-rows">${ranked.length?ranked.slice(0,3).map(b=>`<button class="fx-row block-row" data-block="${b.id}"><span class="fx-letter">${b.name.slice(-1)}</span><span class="block-info"><b>${b.name}</b><span>${b.variety}</span></span><span class="block-dd">${ctx.num(ctx.status(b.id).dd_since_biofix,1)}<small>${ctx.num(Math.max(0,ctx.timeline.thresholds.spray_open_dd-ctx.status(b.id).dd_since_biofix),1)} DD to go</small></span>${ctx.icon('chev',16)}</button>`).join(''):`<div class="empty-copy">${ctx.blocks.some(b=>ctx.status(b.id).biofix_date)?'No blocks currently approaching their first window.':'No confirmed biofix yet. The orchard is being monitored.'}</div>`}</div></section>`}
function overview(ctx){return `${kpis(ctx)}<div class="overview-grid"><section class="fx-card atlas-card"><div class="fx-cardhead"><div><h2>Orchard atlas</h2><div class="fx-small">Nashoba Ridge / 24.8 acres</div></div><button class="text-button" data-action="presentation">Explore in 3D ${ctx.icon('expand',15)}</button></div>${window.FOFarm.map(ctx)}<div class="atlas-foot"><span><i class="legend-swatch"></i>Monitoring / accumulating</span><span><i class="legend-swatch amber"></i>Open window</span><span class="fx-small">Click a block to inspect</span></div></section>${selectedCard(ctx)}</div><div class="overview-bottom">${window.FOPanels.flight(ctx,{compact:true})}${nextBlocks(ctx)}</div><div class="species-ribbon">${window.FOFarm.legend(ctx)}</div>`}
function orchard(ctx){return `<div class="overview-grid orchard-detail"><section class="fx-card atlas-card"><div class="fx-cardhead"><div><h2>The whole orchard</h2><div class="fx-small">Six growing blocks / 18 monitoring traps</div></div><span class="fx-pill">Schematic farm</span></div>${window.FOFarm.map(ctx,{large:true})}<div class="atlas-foot"><span>Tap a block or use the cards below</span><span>${ctx.esc(speciesNames[ctx.species])} counts for ${ctx.dateLabel(ctx.day.date)}</span></div></section>${selectedCard(ctx)}</div><div class="block-portfolio">${ctx.blocks.map(b=>{const s=ctx.status(b.id);return `<button class="fx-card portfolio-card ${ctx.block===b.id?'selected':''}" data-block="${b.id}" aria-pressed="${ctx.block===b.id}"><div class="fx-between"><span class="fx-letter">${b.name.slice(-1)}</span><span class="fx-small">${b.acres} acres</span></div><h3>${b.variety}</h3><div class="fx-number">${ctx.num(s.dd_since_biofix,s.dd_since_biofix%1?1:0)}<small> DD</small></div><span class="status-label status-${s.status}">${statusNames[s.status]}</span><div class="fx-progress"><i style="width:${Math.min(100,s.dd_since_biofix/ctx.timeline.thresholds.spray_close_dd*100)}%"></i></div><div class="fx-small">${ctx.count(b.id)} ${ctx.esc(speciesNames[ctx.species].toLowerCase())} today</div></button>`}).join('')}</div><div class="species-ribbon">${window.FOFarm.legend(ctx)}</div>`}
function nav(ctx){return `<aside class="fx-nav app-nav"><a class="fx-brand" href="?date=${ctx.day.date}&focus=${ctx.block}&tab=overview" aria-label="FieldOps overview"><i class="fx-logo"></i>FieldOps<span class="brand-dot"></span></a><div class="workspace-label">Orchard intelligence</div><nav class="fx-navlinks" aria-label="Dashboard sections">${tabs.map(([id,name,ic])=>`<button id="nav-${id}" class="fx-link ${ctx.tab===id?'fx-active':''}" data-action="navigate" data-tab="${id}" ${ctx.tab===id?'aria-current="page"':''}>${ctx.icon(ic,19)}<span>${name}</span>${id==='overview'?'<span class="nav-tiny">01</span>':''}</button>`).join('')}</nav><div class="nav-film"><span class="workspace-label">The orchard</span><button class="fx-link" data-action="presentation">${ctx.icon('play',19)}<span>3D farm</span></button></div><div class="nav-orchard"><div class="orchard-emblem">${ctx.icon('leaf',25)}</div><b>Nashoba Ridge</b><span>Bolton, Massachusetts</span><div class="nav-season"><i></i>2026 demo season</div></div><div class="nav-meta"><span>Local data</span><span>Built for the orchard</span></div></aside>`}
function toolbar(ctx){return `<header class="fx-top app-top"><span class="crumb">Workspace <span>/</span> <b>${tabs.find(t=>t[0]===ctx.tab)[1]}</b></span><span class="fx-spacer"></span><span class="dataset-badge"><i></i>Demo season</span><button id="theme-toggle" class="icon-button" data-action="theme" aria-label="Switch to ${document.documentElement.dataset.theme==='dark'?'light':'dark'} theme">${ctx.icon(document.documentElement.dataset.theme==='dark'?'sun':'moon',18)}</button><button class="icon-button" data-action="fullscreen" aria-label="Toggle fullscreen">${ctx.icon('expand',18)}</button><span class="avatar" title="Nashoba Ridge workspace">NR</span></header>`}
function filterbar(ctx){return `<div class="filterbar"><label class="filter-control">${ctx.icon('cal',16)}<span class="sr-only">Snapshot date</span><input id="snapshot-date" type="date" min="${data.days[0].date}" max="${data.days.at(-1).date}" value="${ctx.day.date}"></label><label class="filter-control"><span class="fx-small">Block</span><select id="block-select" aria-label="Selected block">${ctx.blocks.map(b=>`<option value="${b.id}" ${b.id===ctx.block?'selected':''}>${b.name} · ${b.variety}</option>`).join('')}</select></label><label class="filter-control"><span class="sr-only">Species</span><select id="species-select" aria-label="Species">${Object.entries(speciesNames).map(([k,v])=>`<option value="${k}" ${k===ctx.species?'selected':''}>${v}</option>`).join('')}</select></label><span class="filter-asof">${ctx.dateLabel(ctx.day.date,{weekday:'long',month:'long',day:'numeric'})}</span><button class="text-button reset-shot" data-action="reset">Reset demo view</button></div>`}
function replayBar(ctx){return `<div class="season-dock" aria-label="Season playback"><button id="play-season" class="dock-play" data-action="play" aria-label="${state.playing?'Pause':'Play season'}">${ctx.icon(state.playing?'pause':'play',15)}<span>${state.playing?'Pause':'Play season'}</span></button><button class="icon-button" data-action="back" aria-label="Previous day">${ctx.icon('back',16)}</button><input id="season-scrub" type="range" min="0" max="${data.days.length-1}" value="${ctx.index}" aria-label="Season date" aria-valuetext="${ctx.dateLabel(ctx.day.date)}"><button class="icon-button" data-action="forward" aria-label="Next day">${ctx.icon('chev',16)}</button><span class="dock-date">${ctx.dateLabel(ctx.day.date)}</span><button class="dock-next" data-action="next-event">Next milestone ${ctx.icon('chev',14)}</button><select id="replay-speed" aria-label="Replay speed"><option value="1" ${state.speed===1?'selected':''}>1×</option><option value="2" ${state.speed===2?'selected':''}>2×</option><option value="0.5" ${state.speed===.5?'selected':''}>0.5×</option></select></div>`}
function explorerInspector(ctx){
 const b=ctx.blocks.find(b=>b.id===ctx.block),s=ctx.status(),th=ctx.timeline.thresholds;
 return `<div class="explorer-inspector-head"><span class="explorer-block-letter">${b.name.slice(-1)}</span><div><span class="explorer-eyebrow">SELECTED BLOCK</span><h2>${ctx.esc(b.name)} <span>/ ${ctx.esc(b.variety)}</span></h2></div><span class="explorer-status status-${s.status}">${statusNames[s.status]}</span></div><div class="explorer-readings"><div><strong>${ctx.num(ctx.count(b.id))}</strong><span>${ctx.esc(speciesNames[ctx.species].toLowerCase())} today</span></div><div><strong>${ctx.num(s.dd_since_biofix,s.dd_since_biofix%1?1:0)}<small> DD</small></strong><span>since codling biofix</span></div></div><div class="explorer-inspector-meta"><span>${b.acres} acres · ${b.traps.length} traps</span><span>${s.status==='accumulating'&&s.projected_open?'Window around '+ctx.dateLabel(s.projected_open):s.status==='spray_window'?th.spray_open_dd+'–'+th.spray_close_dd+' DD window':'Biofix '+ctx.dateLabel(s.biofix_date)}</span></div><button class="explorer-ask" data-action="ask" data-question="Explain the timing for ${ctx.esc(b.name)}">${ctx.icon('mic',15)} Talk about this block ${ctx.icon('chev',15)}</button>`;
}
function explorerBlocks(ctx){return ctx.blocks.map(b=>`<button data-action="map-block" data-block-id="${b.id}" aria-pressed="${ctx.block===b.id}" aria-label="Focus ${ctx.esc(b.name)}" class="explorer-block-chip ${ctx.block===b.id?'selected':''}"><i class="status-${ctx.status(b.id).status}"></i>${b.name}</button>`).join('')}
function presentation(ctx){return `<div class="explorer-page"><div id="farm3d-scene" class="explorer-scene" aria-label="Interactive 3D orchard"></div><header class="explorer-header"><a class="fx-brand" href="#" data-action="exit-presentation"><i class="fx-logo"></i>FieldOps<span class="explorer-brand-divider"></span><small>Farm explorer</small></a><div class="explorer-location"><b>Nashoba Ridge</b><span>Bolton, Massachusetts</span></div><div class="explorer-header-actions"><label class="explorer-date">${ctx.icon('cal',15)}<input id="explorer-date" type="date" value="${ctx.day.date}" min="${data.days[0].date}" max="${data.days.at(-1).date}" aria-label="3D farm snapshot date"></label><button class="explorer-icon" data-action="theme" aria-label="Switch theme">${ctx.icon('sun',18)}</button><button class="explorer-exit" data-action="exit-presentation">${ctx.icon('close',17)}<span>Exit 3D</span></button></div></header><main id="main-content" class="explorer-overlays"><section class="explorer-intro"><span class="explorer-eyebrow">AN ORCHARD IN PERSPECTIVE</span><h1>Closer to<br>your orchard.</h1><p>Explore the land.<br>Understand every signal.</p></section><nav id="explorer-blocks" class="explorer-blocks" aria-label="Focus an orchard block">${explorerBlocks(ctx)}</nav><section id="explorer-inspector" class="explorer-inspector" aria-label="Selected block details">${explorerInspector(ctx)}</section><div class="explorer-controls" aria-label="3D map controls"><button data-action="map-home" aria-label="Reset farm view" title="Reset view (R)">${ctx.icon('home',19)}</button><span></span><button data-action="map-zoom-in" aria-label="Zoom in" title="Zoom in">+</button><button data-action="map-zoom-out" aria-label="Zoom out" title="Zoom out">−</button><span></span><button data-action="map-top" aria-label="Top-down view" title="Top-down view (T)">${ctx.icon('grid',19)}</button><button data-action="map-orbit" aria-label="Angled 3D view" title="Angled 3D view">${ctx.icon('expand',19)}</button><span></span><button data-action="map-tour" aria-label="Start orbit tour" aria-pressed="false" title="Orbit tour">${ctx.icon('play',18)}</button></div><div class="explorer-navigation-note"><span class="explorer-compass">N ↑</span><span>Drag to orbit <i>·</i> Scroll to zoom <i>·</i> Shift + drag to pan</span><button data-action="map-home">Reset view</button></div><div class="explorer-provenance">SCHEMATIC ORCHARD <span>·</span> DEMO SEASON</div></main></div>`}
function syncExplorer(ctx){$('explorer-inspector').innerHTML=explorerInspector(ctx);$('explorer-blocks').innerHTML=explorerBlocks(ctx);$('explorer-date').value=ctx.day.date;mapController.update(ctx)}
function setMapTour(enabled){mapController?.setAutoRotate(enabled);const b=document.querySelector('[data-action="map-tour"]');if(b){b.setAttribute('aria-pressed',String(enabled));b.setAttribute('aria-label',enabled?'Stop orbit tour':'Start orbit tour');b.title=enabled?'Stop orbit tour':'Orbit tour';b.innerHTML=context().icon(enabled?'pause':'play',18)}}
function render(){if(rendering)return;rendering=true;const active=document.activeElement?.id,ctx=context();document.body.classList.toggle('is-playing',state.playing);document.body.classList.toggle('is-cinema',state.presentation);const [heading,sub]=title(ctx);let html;const reuseMap=state.presentation&&mapController&&$('farm3d-scene');if(reuseMap)syncExplorer(ctx);else if(state.presentation)html=presentation(ctx);else{const contents={overview:()=>overview(ctx),orchard:()=>orchard(ctx),pests:()=>window.FOPanels.renderPests(ctx),traps:()=>window.FOPanels.renderTraps(ctx),timing:()=>window.FOPanels.renderTiming(ctx),intelligence:()=>window.FOIntelligence.render(ctx)};html=`<div class="fx-app">${nav(ctx)}<div class="fx-work app-work">${toolbar(ctx)}<main id="main-content" class="fx-content app-content" tabindex="-1"><div class="fx-title"><div><span class="page-eyebrow">Nashoba Ridge / Season 2026</span><h1>${heading}</h1><p>${sub}</p></div><button class="fx-button fx-quiet export-button" data-action="export">${ctx.icon('download',16)} Export snapshot</button></div>${filterbar(ctx)}<div id="tab-panel" aria-label="${ctx.esc(tabs.find(t=>t[0]===ctx.tab)[1])}">${contents[ctx.tab]()}</div><div class="fx-footer app-footer"><span>FieldOps / Orchard intelligence</span><span>Committed demo data • Decisions from the degree-day model</span></div></main>${replayBar(ctx)}</div></div>`}
if(!reuseMap){if(mapController){mapController.destroy();mapController=null}$('app').innerHTML=html;if(state.presentation&&window.FOFarm3D)mapController=window.FOFarm3D.mount($('farm3d-scene'),ctx)}const navStrip=document.querySelector('.fx-navlinks'),activeTab=$('nav-'+ctx.tab);if(navStrip&&activeTab&&navStrip.scrollWidth>navStrip.clientWidth){const desired=activeTab.offsetLeft-navStrip.offsetLeft-navStrip.clientWidth/2+activeTab.clientWidth/2;navStrip.scrollLeft=Math.max(0,desired)}window.FOPanels?.bind($('app'),ctx);window.dispatchEvent(new CustomEvent('fieldops:change',{detail:ctx}));if(active&&$(active))$(active).focus({preventScroll:true});rendering=false;}
function exportCSV(){const ctx=context();const rows=[['date','block','variety','acres','species','count_today','count_7_days','codling_status','codling_degree_days','codling_biofix','estimated_window_open'],...ctx.blocks.map(b=>[ctx.day.date,b.name,b.variety,b.acres,ctx.species,ctx.count(b.id),ctx.weekly(b.id),ctx.status(b.id).status,ctx.status(b.id).dd_since_biofix,ctx.status(b.id).biofix_date||'',ctx.status(b.id).projected_open||''])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=u;a.download=`fieldops-${ctx.day.date}-${ctx.species}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Snapshot exported as CSV')}
$('app').addEventListener('click',e=>{const block=e.target.closest('[data-block]');if(block){update({block:block.dataset.block});return}const species=e.target.closest('[data-species]');if(species){update({species:species.dataset.species});return}const button=e.target.closest('[data-action]');if(!button)return;const a=button.dataset.action;if(a==='navigate')update({tab:button.dataset.tab});if(a==='ask')actions.openAgent(button.dataset.question);if(a==='theme'){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('fieldops-theme',document.documentElement.dataset.theme)}catch{}render()}if(a==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('Fullscreen is unavailable in this browser'))}if(a==='export')exportCSV();if(a==='play')setPlaying(!state.playing);if(a==='back'||a==='forward'){setPlaying(false);if(a==='back')update({index:state.index-1});else step(state.index+1)}if(a==='next-event'){setPlaying(false);const next=data.days.findIndex((d,i)=>i>state.index&&d.events.length);step(next<0?data.days.length-1:next)}if(a==='reset'){setPlaying(false);update({index:dateIndex('2026-06-04'),block:'block-c',species:'codling_moth'})}if(a==='presentation'){setPlaying(false);update({presentation:true});window.scrollTo(0,0)}if(a==='exit-presentation'){e.preventDefault();update({presentation:false})}if(a==='map-home'){setMapTour(false);mapController?.home()}if(a==='map-top'){setMapTour(false);mapController?.setView('top')}if(a==='map-orbit'){setMapTour(false);mapController?.setView('orbit')}if(a==='map-zoom-in')mapController?.zoom(-1);if(a==='map-zoom-out')mapController?.zoom(1);if(a==='map-tour')setMapTour(!mapController?.getState().autoRotate);if(a==='map-block'){setMapTour(false);update({block:button.dataset.blockId});mapController?.focus(state.block)}});
$('app').addEventListener('change',e=>{if(e.target.id==='snapshot-date'||e.target.id==='explorer-date'){const i=dateIndex(e.target.value);if(i>=0){setPlaying(false);update({index:i})}}if(e.target.id==='block-select')update({block:e.target.value});if(e.target.id==='species-select')update({species:e.target.value});if(e.target.id==='replay-speed'){state.speed=Number(e.target.value);if(state.playing)setPlaying(true)}});
$('app').addEventListener('input',e=>{if(e.target.id==='season-scrub'){clearInterval(timer);state.playing=false;update({index:Number(e.target.value)})}});
$('app').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-block]:not(button)')){e.preventDefault();update({block:e.target.dataset.block})}});
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,dialog,[role=dialog]')||e.target.isContentEditable)return;if(e.key==='Escape'&&state.presentation)update({presentation:false});if(e.code==='Space'&&e.target===document.body&&!state.presentation){e.preventDefault();setPlaying(!state.playing)}if(state.presentation&&e.key.toLowerCase()==='r'){setMapTour(false);mapController?.home()}if(state.presentation&&e.key.toLowerCase()==='t'){setMapTour(false);mapController?.setView('top')}});
$('app').addEventListener('pointerdown',e=>{if(e.target.closest('#farm3d-scene'))setMapTour(false)},true);
window.addEventListener('pagehide',()=>mapController?.destroy());
render();window.FOIntelligence.mount(context);url();
})();
