#!/usr/bin/env python3
"""Build offline dashboard JS twins from committed trap references and history.

Run from any directory. No source records are invented or interpolated.
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'dashboard' / 'data'

def write(name, global_name, value):
    OUT.mkdir(exist_ok=True)
    payload = json.dumps(value, separators=(',', ':'), ensure_ascii=True)
    (OUT / name).write_text('// Generated by dashboard/tools/build_dashboard_data.py; do not edit.\n'
                            f'window.{global_name} = {payload};\n')

def main():
    refs = json.loads((ROOT / 'data/traps/manifest.json').read_text())
    write('trap-reference.js', 'FIELDOPS_TRAP_REFERENCE', refs)
    with (ROOT / 'data/history.csv').open(newline='') as source:
        rows = list(csv.DictReader(source))
    records = [[r['timestamp'], r['trap_id'], r['lure'], r['species'], int(r['count']),
                float(r['tmin_f']), float(r['tmax_f'])] for r in rows]
    history = {'source': 'data/history.csv', 'columns': ['timestamp', 'trap_id', 'lure',
               'species', 'count', 'tmin_f', 'tmax_f'], 'records': records,
               'years': sorted({int(r['timestamp'][:4]) for r in rows}),
               'species': sorted({r['species'] for r in rows}),
               'traps': sorted({r['trap_id'] for r in rows})}
    write('history.js', 'FIELDOPS_HISTORY', history)
    print(f'Built {len(refs)} image references and {len(records)} historical records.')

if __name__ == '__main__':
    main()
